T_DATA_PLATFORM:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{env_var('DBT_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('DBT_ROLE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS') |as_number }}"
      client_session_keep_alive: "{{ env_var('DBT_CLIENT_SESSION_KEEP_ALIVE') |as_bool}}"
      query_tag: "{{ env_var('DBT_QUERY_TAG') }}"

elementary:
  outputs:
    default:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{env_var('DBT_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('DBT_ROLE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      # schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS') |as_number }}"
      client_session_keep_alive: "{{ env_var('DBT_CLIENT_SESSION_KEEP_ALIVE') |as_bool}}"
      query_tag: "{{ env_var('DBT_QUERY_TAG') }}"
      schema: "audit_DPF"
      threads: 10
