t_retail:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "data-plateforme-423614"
      dataset: "marketing"
      # dataset: "{{ env_var('BQ_DATASET_DEV') }}"
      threads: 4
      location: europe-west1

    test:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT_TEST') }}"
      dataset: "{{ env_var('BQ_DATASET_TEST') }}"
      threads: 4
      location: europe-west1

    pprod:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT_PPROD') }}"
      dataset: "{{ env_var('BQ_DATASET_PPROD') }}"
      threads: 4
      location: europe-west1

    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('BQ_PROJECT_PROD') }}"
      dataset: "{{ env_var('BQ_DATASET_PROD') }}"
      threads: 4
      location: europe-west1
