T_DATA_PLATFORM:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: khwrkrv-ku13850
      user: USR_DBT_SRV_DEV
      
      private_key_path: /home/djawed/workspace/dbt_user_secret_key/rsa_key.p8
      private_key_passphrase: oObbBTDSMjwLLKWZiaexaIdXQ

      role: accountadmin
      database: marketing
      warehouse: compute_wh
      schema: DEV_ANALYTICS
      threads: 10
      client_session_keep_alive: False
      query_tag: DBT_ENV_DEV

    