T_DATA_PLATFORM:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      #password: 'H8MZRqa8gEe/kvHzvJ+Giq94DuCYoQXmfbb$Xnt'
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{env_var('DBT_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: elementary
      threads: "{{ env_var('SNOWFLAKE_THREADS') |as_number }}"
      client_session_keep_alive: "{{ env_var('SNOWFLAKE_CLIENT_SESSION_KEEP_ALIVE') |as_bool}}"
      query_tag: "{{ env_var('SNOWFLAKE_QUERY_TAG') }}"

elementary:
  outputs:
    default:
      type: "snowflake"
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      #password: 'H8MZRqa8gEe/kvHzvJ+Giq94DuCYoQXmfbb$Xnt'
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      private_key_passphrase: "{{env_var('DBT_PRIVATE_KEY_PASSPHRASE')}}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: "ELEMENTARY"
      threads: 10